### PR TITLE
Added Option to Queue Changes for after Combat/Death

### PR DESCRIPTION
**Pull request by Mischh**
As mentioned: The Pull Request :)

Adds the Ability (and the Option) to select new abilities in combat/death so that they will be changed upon leaving combat/revival. Selected Abilities appear in the Bottom-Right quarter of the current ability (actually a little smaller).

-Mischh

### CODE REVIEW

**Comment by adamjedlicka** [comment]
Hey @Mischh . Thanks for the pull request, unfortunatelly I don't have WildStar installed and I no longer want to maintain ForgeUI. Would you be willing to maintain it, if I give you acces to GitHub adn Curse?

**Comment by Mischh** [comment]
I can maintain ForgeUI, tho I am not using all of its features. There are some of ForgeUI's Addons, which I replaced myself and/or just simply disabled. I can probably test stuff, if it comes up and fix those things.
I am a little confused right now tho: Is this your repository, or veex's? Have i contacted the wrong person?
-Mischh

**Comment by adamjedlicka** [comment]
Well this is veexes addon but it's on shared repository. You posted it on the right place. So if you don't mind PM me an email on curse and I'll send you acc info.

**Comment by Mischh** [comment]
I'd prefer it the way veex tried it. (making me a contributor on curse and granting me access to this repository)
-Mischh

Who is 'You'? Winty or Toludin?

**Comment by adamjedlicka** [comment]
Yeah thats how I ment it.

I'm Winty btw.

**Comment by veex-ua** [comment]
Hey guys. I'm a bit to late to this discusion. I guess you figured what is going on. I've granted @Mischh access only to this addon repo (ForgeUI_ActionSets) and curse maintainer status. I'm pretty much in the same state as Winty i.e don't have WildStar installed and do not plan to maintain stuff. Anyways, good luck to @Mischh with ForgeUI project and keep it going!

**Pull request merged**
